### ISSUE TITLE
PBS does not quite replace Proxborg

### ISSUE THREAD

**Issue by redmop** [michabbs/proxborg#4]
When you need to upload to a cloud service that PBS does not support, you can with proxborg and rclone/rsync/etc.

**Comment by michabbs** [comment]
Well... you can also do backup with PBS and then rclone it to the cloud.
(And I suggest you should go this way, as PBS is fully supported and proxborg is not... :-))

**Comment by redmop** [comment]
How would I go about sending PBS to cloud storage?

PBS does not support any clouds. With Proxborg, I could efficiently push it up to rsync.net, or anything that rsync/rclone can talk to, or anything that is mountable in linux.

**Comment by michabbs** [comment]
PBS stores its backup in normal folder on your disk. (For example in /srv/pbs, or wherever you want.)
So you may either (a) synchronize this folder with remote location using rclone (good idea) or (b) mount remote location inside this folder and let PBS write directly there (possibly not so good idea - delays, temporary connection problems...).

I go with (a). My other script might be helpful: https://github.com/michabbs/rclone-sync-zfs
